" givm options

" set gui editor font
" set guifont=Courier\ New\ 10
set guifont=consolas\ 10
" set guifont=Monaco\ 10
"
" disable menu bar
set guioptions -=m 
" disable toolbar
set guioptions -=T
"remove right-hand scroll bar
set guioptions-=r
"remove left-hand scroll bar
set guioptions-=L

set shell=powershell
colorscheme delek
