" givm options

" set gui editor font
set guifont=Anonymous\ Pro\ 11
" disable menu bar
set guioptions -=m 
" disable toolbar
set guioptions -=T
"remove right-hand scroll bar
set guioptions-=r
"remove left-hand scroll bar
set guioptions-=L

set shell=powershell
colorscheme spacecamp
